# Global Job Crawler Configuration
# This file defines all implemented job sites and their configurations

sites:
  itviec:
    name: "ITviec"
    description: "Vietnamese IT job platform"
    config_file: "config/itviec_config.yaml"
    crawler_module: "itviecCrawler"
    crawler_function: "crawl_itviec"
    enabled: true
  
  linkedin:
    name: "LinkedIn"
    description: "LinkedIn job search platform"
    config_file: "config/linkedin_config.yaml"
    crawler_module: "linkedinCrawler"
    crawler_function: "crawl_linkedin"
    enabled: true

