# ITviec Crawler Configuration
BASE_URL: "https://itviec.com"

# Browser Configuration
HEADLESS: false
USER_DATA_DIR: "./playwright_user_data"
CHANNEL: "chrome"
NO_VIEWPORT: true

# Timeout Configuration (in milliseconds)
PAGE_LOAD_TIMEOUT: 60000
SELECTOR_TIMEOUT: 30000
NAVIGATION_TIMEOUT: 60000
PAGE_SLEEP_DURATION: 2

# URLs and Paths
PROXIES:
  - "/it-jobs"

# Pagination Configuration
PAGE_LIMIT: 'none'  